Add liquibase
jv-sep23-binov/accommodation-booking-service pull request #7
Opened 2024-01-11 19:19 UTC by Alexander1iubchenko

2024-01-11 23:03 UTC, DevIgork requested changes
primary key can't be null  by defauld and  is_deleted must have defauld value false

2024-01-12 00:15 UTC, DevIgork approved these changes

2024-01-12 07:41 UTC, fedorovychh approved these changes

2024-01-12 07:41 UTC, fedorovychh commented on src/main/resources/db/changelog/changes/06-create-payments-table.yaml
> +                  type: decimal
decimal(18,2) інакше буде виводитись цілим числом

2024-01-12 09:09 UTC, merged